/**
 * Real per-page freshness dates, read from git history.
 *
 * WHY: an AI-visibility crawl found 0 of 4 freshness-relevant sampled pages
 * carrying a publish or modified date. Assistants discount undated pages for
 * recency-sensitive questions ("how much does cleaning cost in 2026"), so the
 * pages we most want quoted were the ones being skipped.
 *
 * The honest way to date ~300 pages is to read each page's true last-commit
 * date rather than stamping `new Date()` at build time — a date that is always
 * "today" is noise, and crawlers learn to ignore it. This module is the shared
 * source of that date: astro.config.mjs uses it for sitemap <lastmod>, and the
 * layouts use it for the visible "Last updated" line, so the two can never
 * disagree.
 *
 * FAIL-SAFE BY DESIGN. Every failure path returns null, and callers render
 * nothing rather than a fabricated date:
 *   - Shallow clone (Vercel's default, git depth 1) would collapse every file's
 *     "last commit" to the newest commit — worse than useless, so we detect it
 *     and disable git dates entirely. Set VERCEL_DEEP_CLONE=1 for real dates.
 *   - No git binary / not a repo (e.g. inside the serverless bundle for the 42
 *     `prerender = false` routes) — disabled the same way, after one cheap
 *     probe that is cached for the process lifetime.
 */
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
// Committed route → last-commit-date map, regenerated by
// scripts/generate-freshness.mjs wherever full git history exists. This is the
// PRIMARY source: Vercel shallow-clones by default, so live `git log` yields
// nothing there, and without the manifest every page would ship undated.
import freshnessManifest from "../data/freshness.json";

// src/lib/pageFreshness.mjs → repo root
const projectRoot = fileURLToPath(new URL("../../", import.meta.url));

function git(args) {
  return execFileSync("git", args, {
    cwd: projectRoot,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

let gitDatesEnabled = null; // lazy: probed once, then cached
function enabled() {
  if (gitDatesEnabled === null) {
    try {
      gitDatesEnabled = git(["rev-parse", "--is-shallow-repository"]) === "false";
    } catch {
      gitDatesEnabled = false;
    }
  }
  return gitDatesEnabled;
}

const gitDateCache = new Map();

/** Last commit date (ISO 8601) for one repo-relative file, or null. */
export function gitDate(relPath) {
  if (!enabled()) return null;
  if (gitDateCache.has(relPath)) return gitDateCache.get(relPath);
  let date = null;
  try {
    if (existsSync(join(projectRoot, relPath))) {
      const iso = git(["log", "-1", "--format=%cI", "--", relPath]);
      if (iso) date = iso;
    }
  } catch {
    /* leave null → caller renders no date */
  }
  gitDateCache.set(relPath, date);
  return date;
}

/**
 * Most recent commit date across several files, for data-driven pages whose
 * content changes when any of their source/data files change.
 *
 * Compares by absolute instant, not string order: `git %cI` emits the
 * committer's local offset (e.g. -05:00), so two ISO strings can sort wrong
 * relative to their true UTC time and pick a stale date.
 */
export function latestGitDate(relPaths) {
  let best = null;
  for (const p of relPaths) {
    const d = gitDate(p);
    if (d && (!best || Date.parse(d) > Date.parse(best))) best = d;
  }
  return best;
}

/**
 * Map a site path (no origin, no trailing slash) to the source file(s) that
 * determine its freshness, and return that git date. Returns null when the path
 * can't be resolved to a file — safe/neutral, the date is simply omitted.
 */
export function lastmodForPath(pathname) {
  const path = String(pathname || "").replace(/\/$/, "") || "/"; // trailingSlash: never

  // 1. Committed manifest — works everywhere, including shallow clones.
  const fromManifest = freshnessManifest[path];
  if (fromManifest) return fromManifest;

  // 2. Live git, for routes added since the manifest was last regenerated.
  if (enabled()) {
    const concrete =
      gitDate(`src/pages${path === "/" ? "/index" : path}.astro`) ??
      gitDate(`src/pages${path}/index.astro`);
    if (concrete) return concrete;
  }

  // 3. /locations/<city>/<slug> combos served by the SSR dynamic route
  //    [city]/[slug].astro have no per-URL file; they inherit the freshness of
  //    the route template plus the data files that drive them.
  if (/^\/locations\/[^/]+\/[^/]+$/.test(path)) {
    return (
      freshnessManifest.__locations_dynamic__ ??
      latestGitDate([
        "src/pages/locations/[city]/[slug].astro",
        "src/data/locations.json",
        "src/data/services.json",
      ])
    );
  }

  return null;
}

/** "August 10, 2026" for display, or null. */
export function formatFreshness(iso) {
  if (!iso) return null;
  const d = new Date(iso);
  if (isNaN(d.getTime())) return null;
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });
}

/** "2026-08-10" for the <time datetime> attribute, or null. */
export function freshnessDateAttr(iso) {
  if (!iso) return null;
  const d = new Date(iso);
  if (isNaN(d.getTime())) return null;
  return d.toISOString().slice(0, 10);
}
