export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  filterCategory: string;
  categoryColor: string;
  date: string;
  readTime: string;
  icon: string;
  image?: string;
}

export const allBlogPosts: BlogPost[] = [
  // 2026 Script Scaffolded Posts
  {
    slug: "top-5-hidden-areas-to-focus-on-during-spring-cleaning-in-athens-al",
    title: "Top 5 Hidden Areas to Focus on During Spring Cleaning in Athens, AL",
    excerpt: "Check back on March 16 2026 for our latest article covering top 5 hidden areas to focus on during spring cleaning in athens, al.",
    category: "Deep Cleaning",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "March 16 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "how-to-prepare-your-nashville-home-for-allergy-season",
    title: "How to Prepare Your Nashville Home for Allergy Season",
    excerpt: "Check back on March 23 2026 for our latest article covering how to prepare your nashville home for allergy season.",
    category: "Allergy/Health",
    filterCategory: "home-health",
    categoryColor: "teal",
    date: "March 23 2026",
    readTime: "5 min read",
    icon: "heart",
  },
  {
    slug: "hiring-an-independent-cleaner-vs-a-professional-cleaning-company-in-mountain-brook",
    title: "Hiring an Independent Cleaner vs. a Professional Cleaning Company in Mountain Brook",
    excerpt: "Check back on March 30 2026 for our latest article covering hiring an independent cleaner vs. a professional cleaning company in Mountain Brook.",
    category: "Educational/Trust",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "March 30 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "move-out-cleaning-requirements-for-huntsville-property-managers",
    title: "Move-Out Cleaning Requirements for Huntsville Property Managers",
    excerpt: "Check back on April 6 2026 for our latest article covering move-out cleaning requirements for huntsville property managers.",
    category: "Move-Out/Real Estate",
    filterCategory: "move-out",
    categoryColor: "purple",
    date: "April 6 2026",
    readTime: "5 min read",
    icon: "home",
  },
  {
    slug: "how-much-value-does-a-deep-clean-add-before-selling-a-home-in-the-shoals",
    title: "How Much Value Does a Deep Clean Add Before Selling a Home in the Shoals?",
    excerpt: "Check back on April 13 2026 for our latest article covering how much value does a deep clean add before selling a home in the shoals?.",
    category: "Real Estate",
    filterCategory: "move-out",
    categoryColor: "purple",
    date: "April 13 2026",
    readTime: "5 min read",
    icon: "home",
  },
  {
    slug: "pre-listing-cleaning-checklist-for-middle-tennessee-realtors",
    title: "Pre-Listing Cleaning Checklist for Middle Tennessee Realtors",
    excerpt: "Check back on April 20 2026 for our latest article covering pre-listing cleaning checklist for middle tennessee realtors.",
    category: "B2B/Real Estate",
    filterCategory: "move-out",
    categoryColor: "purple",
    date: "April 20 2026",
    readTime: "5 min read",
    icon: "home",
  },
  {
    slug: "post-construction-cleaning-what-to-expect-after-a-home-renovation",
    title: "Post-Construction Cleaning: What to Expect After a Home Renovation",
    excerpt: "Check back on April 27 2026 for our latest article covering post-construction cleaning: what to expect after a home renovation.",
    category: "Specialty",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "April 27 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "what-is-included-in-a-professional-move-in-clean",
    title: "What Is Included in a Professional Move-In Clean?",
    excerpt: "Check back on May 4 2026 for our latest article covering what is included in a professional move-in clean?.",
    category: "Educational/Checklist",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "May 4 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "bi-weekly-vs-monthly-house-cleaning-which-is-right-for-you",
    title: "Bi-Weekly vs. Monthly House Cleaning: Which is Right for You?",
    excerpt: "Check back on May 11 2026 for our latest article covering bi-weekly vs. monthly house cleaning: which is right for you?.",
    category: "Pricing/Value",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "May 11 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "how-to-maintain-a-clean-home-with-pets-in-the-house",
    title: "How to Maintain a Clean Home with Pets in the House",
    excerpt: "Check back on May 18 2026 for our latest article covering how to maintain a clean home with pets in the house.",
    category: "Pain Point",
    filterCategory: "home-health",
    categoryColor: "teal",
    date: "May 18 2026",
    readTime: "5 min read",
    icon: "heart",
  },
  {
    slug: "move-out-cleaning-costs-in-nashville-2026-updated-guide",
    title: "Move-Out Cleaning Costs in Nashville: 2026 Updated Guide",
    excerpt: "Check back on May 25 2026 for our latest article covering move-out cleaning costs in nashville: 2026 updated guide.",
    category: "Pricing/Direct Response",
    filterCategory: "industry",
    categoryColor: "pink",
    date: "May 25 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "keeping-your-floors-and-entryways-clean-during-summer-break",
    title: "Keeping Your Floors and Entryways Clean During Summer Break",
    excerpt: "Check back on June 1 2026 for our latest article covering keeping your floors and entryways clean during summer break.",
    category: "Pain Point/Seasonal",
    filterCategory: "holiday",
    categoryColor: "green",
    date: "June 1 2026",
    readTime: "5 min read",
    icon: "gift",
  },
  {
    slug: "office-cleaning-in-mountain-brook-how-a-clean-workspace-boosts-productivity",
    title: "Office Cleaning in Mountain Brook: How a Clean Workspace Boosts Productivity",
    excerpt: "Check back on June 8 2026 for our latest article covering office cleaning in Mountain Brook: how a clean workspace boosts productivity.",
    category: "Commercial/B2B",
    filterCategory: "industry",
    categoryColor: "indigo",
    date: "June 8 2026",
    readTime: "5 min read",
    icon: "building",
  },
  {
    slug: "what-does-bonded-and-insured-mean-when-hiring-a-cleaning-service",
    title: "What Does \"Bonded and Insured\" Mean When Hiring a Cleaning Service?",
    excerpt: "Check back on June 15 2026 for our latest article covering what does \"bonded and insured\" mean when hiring a cleaning service?.",
    category: "Trust/Educational",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "June 15 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "short-term-rental-cleaning-in-the-shoals-turnaround-best-practices",
    title: "Short-Term Rental Cleaning in the Shoals: Turnaround Best Practices",
    excerpt: "Check back on June 22 2026 for our latest article covering short-term rental cleaning in the shoals: turnaround best practices.",
    category: "Commercial/Airbnb",
    filterCategory: "industry",
    categoryColor: "indigo",
    date: "June 22 2026",
    readTime: "5 min read",
    icon: "building",
  },
  {
    slug: "the-cost-of-commercial-cleaning-services-in-nashville-in-2026",
    title: "The Cost of Commercial Cleaning Services in Nashville in 2026",
    excerpt: "Check back on June 29 2026 for our latest article covering the cost of commercial cleaning services in nashville in 2026.",
    category: "Commercial Pricing",
    filterCategory: "industry",
    categoryColor: "indigo",
    date: "June 29 2026",
    readTime: "5 min read",
    icon: "building",
  },
  {
    slug: "why-baseboards-and-blinds-dusting-makes-a-difference",
    title: "Why Baseboards and Blinds Dusting Makes a Difference",
    excerpt: "Check back on July 6 2026 for our latest article covering why baseboards and blinds dusting makes a difference.",
    category: "Deep Cleaning",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "July 6 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "kitchen-appliance-deep-cleaning-ovens-refrigerators-and-layouts",
    title: "Kitchen Appliance Deep Cleaning: Ovens, Refrigerators, and Layouts",
    excerpt: "Check back on July 13 2026 for our latest article covering kitchen appliance deep cleaning: ovens, refrigerators, and layouts.",
    category: "Specialty",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "July 13 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "the-military-precision-approach-to-cleaning-your-home",
    title: "The Military-Precision Approach to Cleaning Your Home",
    excerpt: "Check back on July 20 2026 for our latest article covering the military-precision approach to cleaning your home.",
    category: "Brand Story/Trust",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "July 20 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "carpet-upholstery-care-when-to-add-it-to-your-cleaning-service",
    title: "Carpet & Upholstery Care: When to Add It to Your Cleaning Service",
    excerpt: "Check back on July 27 2026 for our latest article covering carpet & upholstery care: when to add it to your cleaning service.",
    category: "Specialty/Upsell",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "July 27 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "reclaiming-your-weekends-finding-the-right-bi-weekly-cleaner-in-nashville",
    title: "Reclaiming Your Weekends: Finding the Right Bi-Weekly Cleaner in Nashville",
    excerpt: "Check back on August 3 2026 for our latest article covering reclaiming your weekends: finding the right bi-weekly cleaner in nashville.",
    category: "Value/Time-Saving",
    filterCategory: "industry",
    categoryColor: "pink",
    date: "August 3 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "back-to-school-cleaning-reset-for-busy-madison-county-parents",
    title: "Back-to-School Cleaning Reset for Busy Madison County Parents",
    excerpt: "Check back on August 10 2026 for our latest article covering back-to-school cleaning reset for busy madison county parents.",
    category: "Pain Point",
    filterCategory: "home-health",
    categoryColor: "teal",
    date: "August 10 2026",
    readTime: "5 min read",
    icon: "heart",
  },
  {
    slug: "how-to-organize-and-sanitize-mudrooms-and-entryways",
    title: "How to Organize and Sanitize Mudrooms and Entryways",
    excerpt: "Check back on August 17 2026 for our latest article covering how to organize and sanitize mudrooms and entryways.",
    category: "Tidying/Educational",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "August 17 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "how-to-budget-for-house-cleaning-services-in-2026",
    title: "How to Budget for House Cleaning Services in 2026",
    excerpt: "Check back on August 24 2026 for our latest article covering how to budget for house cleaning services in 2026.",
    category: "Pricing/Conversion",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "August 24 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "signs-its-time-to-fire-your-current-cleaning-service",
    title: "Signs It's Time to Fire Your Current Cleaning Service",
    excerpt: "Check back on August 31 2026 for our latest article covering signs it's time to fire your current cleaning service.",
    category: "Comparison/Direct Response",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "August 31 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "eco-friendly-cleaning-products-vs-traditional-chemicals-what-we-use",
    title: "Eco-Friendly Cleaning Products vs. Traditional Chemicals: What We Use",
    excerpt: "Check back on September 7 2026 for our latest article covering eco-friendly cleaning products vs. traditional chemicals: what we use.",
    category: "Educational",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "September 7 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "how-professional-cleaning-reduces-indoor-air-pollution",
    title: "How Professional Cleaning Reduces Indoor Air Pollution",
    excerpt: "Check back on September 14 2026 for our latest article covering how professional cleaning reduces indoor air pollution.",
    category: "Health/AEO",
    filterCategory: "home-health",
    categoryColor: "teal",
    date: "September 14 2026",
    readTime: "5 min read",
    icon: "heart",
  },
  {
    slug: "is-a-first-time-deep-clean-necessary-before-routine-service",
    title: "Is a First-Time Deep Clean Necessary Before Routine Service?",
    excerpt: "Check back on September 21 2026 for our latest article covering is a first-time deep clean necessary before routine service?.",
    category: "FAQ/Conversion",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "September 21 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "end-of-summer-deep-clean-checklist-for-jefferson-county-properties",
    title: "End of Summer Deep Clean Checklist for Jefferson County Properties",
    excerpt: "Check back on September 28 2026 for our latest article covering end of summer deep clean checklist for jefferson county properties.",
    category: "Seasonal",
    filterCategory: "holiday",
    categoryColor: "green",
    date: "September 28 2026",
    readTime: "5 min read",
    icon: "gift",
  },
  {
    slug: "preparing-your-guest-room-and-bathrooms-for-holiday-visitors",
    title: "Preparing Your Guest Room and Bathrooms for Holiday Visitors",
    excerpt: "Check back on October 5 2026 for our latest article covering preparing your guest room and bathrooms for holiday visitors.",
    category: "Hosting/Seasonal",
    filterCategory: "holiday",
    categoryColor: "green",
    date: "October 5 2026",
    readTime: "5 min read",
    icon: "gift",
  },
  {
    slug: "fall-deep-cleaning-combating-dust-and-spider-webs",
    title: "Fall Deep Cleaning: Combating Dust and Spider Webs",
    excerpt: "Check back on October 12 2026 for our latest article covering fall deep cleaning: combating dust and spider webs.",
    category: "Deep Cleaning",
    filterCategory: "industry",
    categoryColor: "pink",
    date: "October 12 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "how-early-should-i-book-a-pre-holiday-house-cleaning",
    title: "How Early Should I Book a Pre-Holiday House Cleaning?",
    excerpt: "Check back on October 19 2026 for our latest article covering how early should i book a pre-holiday house cleaning?.",
    category: "Urgency/Direct Response",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "October 19 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "the-ultimate-pre-party-cleaning-checklist",
    title: "The Ultimate Pre-Party Cleaning Checklist",
    excerpt: "Check back on October 26 2026 for our latest article covering the ultimate pre-party cleaning checklist.",
    category: "Hosting",
    filterCategory: "holiday",
    categoryColor: "green",
    date: "October 26 2026",
    readTime: "5 min read",
    icon: "gift",
  },
  {
    slug: "getting-your-kitchen-holiday-ready-a-deep-clean-guide",
    title: "Getting Your Kitchen Holiday-Ready: A Deep Clean Guide",
    excerpt: "Check back on November 2 2026 for our latest article covering getting your kitchen holiday-ready: a deep clean guide.",
    category: "Specialty",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "November 2 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "why-we-value-military-precision-accountability-veterans-day-feature",
    title: "Why We Value Military-Precision Accountability (Veterans Day Feature)",
    excerpt: "Check back on November 9 2026 for our latest article covering why we value military-precision accountability (veterans day feature).",
    category: "Brand Story/Trust",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "November 9 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "post-event-cleaning-services-for-corporate-holiday-parties",
    title: "Post-Event Cleaning Services for Corporate Holiday Parties",
    excerpt: "Check back on November 16 2026 for our latest article covering post-event cleaning services for corporate holiday parties.",
    category: "Commercial/Post-Event",
    filterCategory: "industry",
    categoryColor: "indigo",
    date: "November 16 2026",
    readTime: "5 min read",
    icon: "building",
  },
  {
    slug: "black-friday-special-the-gift-of-a-clean-home",
    title: "Black Friday Special: The Gift of a Clean Home",
    excerpt: "Check back on November 23 2026 for our latest article covering black friday special: the gift of a clean home.",
    category: "Promo/Conversion",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "November 23 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "surviving-the-post-thanksgiving-mess-kitchen-reset",
    title: "Surviving the Post-Thanksgiving Mess: Kitchen Reset",
    excerpt: "Check back on November 30 2026 for our latest article covering surviving the post-thanksgiving mess: kitchen reset.",
    category: "Pain Point",
    filterCategory: "home-health",
    categoryColor: "teal",
    date: "November 30 2026",
    readTime: "5 min read",
    icon: "heart",
  },
  {
    slug: "last-minute-touches-before-your-in-laws-arrive",
    title: "Last-Minute Touches Before Your In-Laws Arrive",
    excerpt: "Check back on December 7 2026 for our latest article covering last-minute touches before your in-laws arrive.",
    category: "Humor/Pain Point",
    filterCategory: "home-health",
    categoryColor: "teal",
    date: "December 7 2026",
    readTime: "5 min read",
    icon: "heart",
  },
  {
    slug: "giving-the-gift-of-clean-how-house-cleaning-gift-certificates-work",
    title: "Giving the Gift of Clean: How House Cleaning Gift Certificates Work",
    excerpt: "Check back on December 14 2026 for our latest article covering giving the gift of clean: how house cleaning gift certificates work.",
    category: "Gifting/Conversion",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "December 14 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "setting-up-a-cleaning-schedule-for-the-new-year",
    title: "Setting Up a Cleaning Schedule for the New Year",
    excerpt: "Check back on December 21 2026 for our latest article covering setting up a cleaning schedule for the new year.",
    category: "Planning/Recurring Booking",
    filterCategory: "industry",
    categoryColor: "pink",
    date: "December 21 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  {
    slug: "year-in-review-our-commitment-to-the-shoals-community-in-2027",
    title: "Year-In-Review: Our Commitment to the Shoals Community in 2027",
    excerpt: "Check back on December 28 2026 for our latest article covering year-in-review: our commitment to the shoals community in 2027.",
    category: "Brand Story",
    filterCategory: "industry",
    categoryColor: "blue",
    date: "December 28 2026",
    readTime: "5 min read",
    icon: "lightbulb",
  },
  // Location-specific service pages (added to fix orphan links)
  {
    slug: "move-out-cleaning-nashville-tn",
    title: "Move-Out Cleaning in Nashville, TN | Get Your Deposit Back",
    excerpt: "Moving out of your Nashville rental? Our professional move-out cleaning service helps you get your full security deposit back with a thorough, inspection-ready clean.",
    category: "Move-Out/Real Estate",
    filterCategory: "move-out",
    categoryColor: "purple",
    date: "May 2025",
    readTime: "10 min read",
    icon: "home",
  },
  {
    slug: "move-out-cleaning-athens-al",
    title: "Move-Out Cleaning in Athens, AL | Get Your Deposit Back",
    excerpt: "Professional move-out cleaning in Athens, AL. We handle everything landlords inspect so you can focus on your move and get your full deposit returned.",
    category: "Move-Out/Real Estate",
    filterCategory: "move-out",
    categoryColor: "purple",
    date: "May 2025",
    readTime: "8 min read",
    icon: "home",
  },
  {
    slug: "commercial-cleaning-athens-al",
    title: "Commercial Cleaning Services in Athens, AL",
    excerpt: "Reliable commercial cleaning for offices, retail spaces, and businesses in Athens, AL. Consistent, professional results on your schedule.",
    category: "Commercial/B2B",
    filterCategory: "industry",
    categoryColor: "indigo",
    date: "July 2025",
    readTime: "8 min read",
    icon: "building",
  },
  {
    slug: "move-out-cleaning-florence-al",
    title: "Move-Out Cleaning in Florence, AL | Get Your Deposit Back",
    excerpt: "Expert move-out cleaning in Florence, AL. We deep clean every area landlords check so you leave with your deposit intact.",
    category: "Move-Out/Real Estate",
    filterCategory: "move-out",
    categoryColor: "purple",
    date: "May 2025",
    readTime: "9 min read",
    icon: "home",
  },
  {
    slug: "commercial-cleaning-huntsville-al",
    title: "Commercial Cleaning Services in Huntsville, AL",
    excerpt: "Professional commercial cleaning for Huntsville businesses. Flexible scheduling, bonded and insured teams, and consistent quality every visit.",
    category: "Commercial/B2B",
    filterCategory: "industry",
    categoryColor: "indigo",
    date: "July 2025",
    readTime: "10 min read",
    icon: "building",
  },
  {
    slug: "commercial-cleaning-florence-al",
    title: "Commercial Cleaning Services in Florence, AL",
    excerpt: "Top-rated commercial cleaning in Florence, AL for offices, retail stores, and professional spaces. Serving the entire Shoals area.",
    category: "Commercial/B2B",
    filterCategory: "industry",
    categoryColor: "indigo",
    date: "July 2025",
    readTime: "9 min read",
    icon: "building",
  },
  // New Scheduled Posts (Weekly from Dec-10 through Jan-28)
  {
    slug: "spring-cleaning-nashville-survival-guide",
    title:
      "The Ultimate Spring Cleaning Survival Guide for Nashville Homeowners",
    excerpt:
      "Conquer pollen season and refresh your Music City home with our comprehensive spring deep cleaning checklist.",
    category: "Seasonal Cleaning",
    filterCategory: "home-health",
    categoryColor: "green",
    date: "January 28, 2026",
    readTime: "8 min read",
    icon: "leaf",
    image: "/images/gallery/bathroom.webp",
  },
  {
    slug: "post-construction-cleaning-mountain-brook-guide",
    title:
      "Surviving the Dust: A Homeowner's Guide to Post-Construction Cleaning in Mountain Brook",
    excerpt:
      "Just finished a renovation? Learn how to safely and effectively remove fine construction dust from every surface of your Mountain Brook home.",
    category: "Post-Construction",
    filterCategory: "move-out",
    categoryColor: "amber",
    date: "July 1, 2026",
    readTime: "7 min read",
    icon: "hard-hat",
    image: "/images/gallery/kitchen.webp",
  },
  {
    slug: "move-out-cleaning-huntsville-guide",
    title:
      "The Stress-Free Move-Out Cleaning Guide for Huntsville Renters (Get Your Deposit Back)",
    excerpt:
      "Moving out of your Rocket City rental? Follow our detailed checklist to ensure you get your full security deposit returned without the stress.",
    category: "Move-Out Guide",
    filterCategory: "move-out",
    categoryColor: "blue",
    date: "January 14, 2026",
    readTime: "6 min read",
    icon: "home",
    image: "/images/gallery/move_out.webp",
  },
  {
    slug: "is-hiring-house-cleaner-worth-it",
    title:
      "Is Hiring a House Cleaner Really Worth the Cost? An Honest Cost-Benefit Analysis",
    excerpt:
      "Debating whether to hire professional cleaners? Weighing the cost against the time saved, reduced stress, and improved health.",
    category: "The Real Cost",
    filterCategory: "industry",
    categoryColor: "purple",
    date: "April 12, 2026",
    readTime: "9 min read",
    icon: "dollar-sign",
    image: "/images/hero-400w.avif",
  },

  {
    slug: "deep-cleaning-cost-shoals-guide",
    title: "How Much Does Deep Cleaning Actually Cost in the Shoals Area?",
    excerpt:
      "A transparent breakdown of deep cleaning costs in Florence, Muscle Shoals, and Tuscumbia—and what you should expect to get for your money.",
    category: "Pricing Guide",
    filterCategory: "industry",
    categoryColor: "gray",
    date: "December 24, 2025",
    readTime: "7 min read",
    icon: "dollar-sign",
    image: "/images/services/Cleaningpic12-303.webp",
  },
  {
    slug: "cleaning-service-missing-spots-what-to-do",
    title: "What to Do When Your Cleaning Service Keeps Missing Spots",
    excerpt:
      "Are your cleaners consistently missing areas? How to have a productive conversation, set expectations, and when it's time to hire someone else.",
    category: "Industry Problems",
    filterCategory: "industry",
    categoryColor: "yellow",
    date: "December 17, 2025",
    readTime: "8 min read",
    icon: "thumbs-down",
    image: "/images/services/Cleaningpic13-309.webp",
  },
  {
    slug: "airbnb-cleaning-nashville-host-guide",
    title:
      "Airbnb Turnover Cleaning Nashville: Host Guide to 5-Star Reviews",
    excerpt:
      "How to find the right vacation rental turnover cleaning service in Nashville and never lose a 5-star rating to a bad clean again. Fast turnovers, linen service, and what top hosts do differently.",
    category: "Short-Term Rentals",
    filterCategory: "rentals",
    categoryColor: "pink",
    date: "April 12, 2026",
    readTime: "9 min read",
    icon: "bed",
    image: "/images/services/Cleaningpic15-312.webp",
  },
  // Existing Posts
  {
    slug: "holiday-hosting-guide-for-moms",
    title:
      "Making Mom Magic: A Guide to Hosting the Holidays (Without the Meltdown)",
    excerpt:
      "You're the CEO of Holiday Magic. This year, we're ditching perfectionism so you can actually enjoy the magic you're creating—not just clean up after it.",
    category: "Holiday Tips",
    filterCategory: "holiday",
    categoryColor: "red",
    date: "December 3, 2025",
    readTime: "5 min read",
    icon: "tree",
    image:
      "https://res.cloudinary.com/dfjneoiaq/image/fetch/f_auto,q_auto,w_400/https://storage.googleapis.com/msgsndr/iKQIBhpKVL2XVPgU7HMd/media/69306779e0f092659261fa82.png",
  },
  {
    slug: "last-minute-holiday-cleaning",
    title:
      "Last-Minute Holiday Cleaning: Quick Guide When Guests Are Coming",
    excerpt:
      "Your mother-in-law just texted that she's arriving in 3 hours. Don't panic—here's how to make your home guest-ready fast with our room-by-room quick-clean guide.",
    category: "Quick Clean Guide",
    filterCategory: "holiday",
    categoryColor: "red",
    date: "November 26, 2025",
    readTime: "7 min read",
    icon: "clock",
    image:
      "https://res.cloudinary.com/dfjneoiaq/image/fetch/f_auto,q_auto,w_400/https://storage.googleapis.com/msgsndr/iKQIBhpKVL2XVPgU7HMd/media/693082241d466e98cf76452a.png",
  },
  {
    slug: "why-your-home-never-stays-clean",
    title: "Why Your Home Never Stays Clean (No Matter How Hard You Try)",
    excerpt:
      "Discover the real reasons your house gets messy so fast and what you can actually do about it. A honest look at the cleaning struggle from professional cleaners.",
    category: "The Cleaning Struggle",
    filterCategory: "home-health",
    categoryColor: "orange",
    date: "November 26, 2025",
    readTime: "8 min read",
    icon: "broom",
    image:
      "https://res.cloudinary.com/dfjneoiaq/image/fetch/f_auto,q_auto,w_400/https://storage.googleapis.com/msgsndr/iKQIBhpKVL2XVPgU7HMd/media/693082247bbd8dad470b199c.png",
  },
  {
    slug: "hidden-cost-of-dirty-house",
    title: "The Hidden Cost of a Dirty House (What It's Really Costing You)",
    excerpt:
      "A messy home costs more than embarrassment. Discover the real financial, health, and emotional toll of living in a dirty house—and what to do about it.",
    category: "The True Price",
    filterCategory: "home-health",
    categoryColor: "purple",
    date: "November 26, 2025",
    readTime: "9 min read",
    icon: "dollar-sign",
    image: "/images/services/Cleaningpic3-308.webp",
  },
  {
    slug: "losing-your-security-deposit",
    title: "Are You About to Lose Your Security Deposit?",
    excerpt:
      "Moving out soon? Learn what landlords really look for during move-out inspections and how to maximize your chances of getting your full deposit back.",
    category: "Move-Out Guide",
    filterCategory: "move-out",
    categoryColor: "blue",
    date: "November 25, 2025",
    readTime: "7 min read",
    icon: "home",
    image: "/images/services/Cleaningpic4-306.webp",
  },
  {
    slug: "why-youre-always-exhausted",
    title: "Why You're Always Exhausted (And Your Home Might Be the Reason)",
    excerpt:
      "The surprising connection between your home environment and your energy levels. Learn how clutter and mess drain you—and what to do about it.",
    category: "Home & Health",
    filterCategory: "home-health",
    categoryColor: "teal",
    date: "November 25, 2025",
    readTime: "8 min read",
    icon: "tired",
    image: "/images/services/Cleaningpic6-305.webp",
  },
  {
    slug: "truth-about-hiring-cleaning-service",
    title: "The Truth About Hiring a Cleaning Service",
    excerpt:
      "What you really need to know before hiring professional cleaners. We share the industry secrets most companies don't want you to know.",
    category: "Industry Secrets",
    filterCategory: "industry",
    categoryColor: "gray",
    date: "November 24, 2025",
    readTime: "10 min read",
    icon: "user-secret",
    image: "/images/services/Cleaningpic7-300.webp",
  },
  {
    slug: "when-life-gets-too-busy",
    title: "When Life Gets Too Busy to Clean",
    excerpt:
      "Work, kids, life demands—there's no time left for cleaning. Here's how to stop feeling guilty and start finding solutions that actually work.",
    category: "Busy Life",
    filterCategory: "home-health",
    categoryColor: "yellow",
    date: "November 24, 2025",
    readTime: "6 min read",
    icon: "running",
    image: "/images/services/Cleaningpic8-311.webp",
  },
  {
    slug: "embarrassed-to-have-people-over",
    title: "Embarrassed to Have People Over?",
    excerpt:
      "If you've been avoiding having guests because of your home's condition, you're not alone. Here's how to break the cycle of shame and isolation.",
    category: "Real Talk",
    filterCategory: "home-health",
    categoryColor: "pink",
    date: "November 23, 2025",
    readTime: "7 min read",
    icon: "users",
    image: "/images/services/Cleaningpic9-304.webp",
  },
  {
    slug: "airbnb-hosts-nightmare",
    title: "The Airbnb Host's Nightmare: Cleaning Between Guests",
    excerpt:
      "Managing turnover cleaning is the #1 stress for short-term rental hosts. Learn how professional turnover services can save your reviews and your sanity.",
    category: "Short-Term Rentals",
    filterCategory: "rentals",
    categoryColor: "red",
    date: "November 22, 2025",
    readTime: "8 min read",
    icon: "bed",
    image: "/images/gallery/move_out.webp",
  },
  {
    slug: "construction-dust-destroying-home",
    title: "Is Construction Dust Destroying Your Home?",
    excerpt:
      "Had recent renovations or construction nearby? That fine dust gets everywhere and can damage your home and health. Here's what you need to know.",
    category: "Post-Construction",
    filterCategory: "move-out",
    categoryColor: "amber",
    date: "November 21, 2025",
    readTime: "7 min read",
    icon: "hard-hat",
    image: "/images/gallery/kitchen.webp",
  },
];
