// City configurations with competitive intelligence
export interface CityConfig {
  lat: string;
  lng: string;
  phone: string;
  state: string;
  stateAbbr: string;
  zips: string;
  radius: string;
  edge: string;
  focusService: string;
  reviewFocus: string;
  searchVolume: string;
}

export const cityConfigs: Record<string, CityConfig> = {
  Huntsville: {
    lat: "34.7304",
    lng: "-86.5861",
    phone: "+1-256-826-1100",
    state: "Alabama",
    stateAbbr: "AL",
    zips: "35801-35816",
    radius: "50000",
    edge: "Pet-safe underserved (only 20% of competitors mention it)",
    focusService: "Pet-Safe Deep Cleaning",
    reviewFocus: "pet-safe deep clean",
    searchVolume: "high",
  },
  Madison: {
    lat: "34.6993",
    lng: "-86.7483",
    phone: "+1-256-826-1100",
    state: "Alabama",
    stateAbbr: "AL",
    zips: "35756-35758",
    radius: "25000",
    edge: "Huntsville overflow market—pet-safe families",
    focusService: "Recurring Pet-Safe Cleaning",
    reviewFocus: "family-friendly cleaning",
    searchVolume: "medium",
  },
  Athens: {
    lat: "34.8026",
    lng: "-86.9717",
    phone: "+1-256-826-1100",
    state: "Alabama",
    stateAbbr: "AL",
    zips: "35611-35614",
    radius: "30000",
    edge: "Limited local competition—pet-safe niche",
    focusService: "Pet-Safe House Cleaning",
    reviewFocus: "reliable local service",
    searchVolume: "low",
  },
  Decatur: {
    lat: "34.6059",
    lng: "-86.9833",
    phone: "+1-256-826-1100",
    state: "Alabama",
    stateAbbr: "AL",
    zips: "35601-35603",
    radius: "50000",
    edge: "Pet-safe fills gap in 70% of competitor listings",
    focusService: "Pet-Safe Move-Out Cleaning",
    reviewFocus: "move-out cleaning",
    searchVolume: "medium",
  },
  "Mountain Brook": {
    lat: "33.4940",
    lng: "-86.7520",
    phone: "+1-256-826-1100",
    state: "Alabama",
    stateAbbr: "AL",
    zips: "35213-35243",
    radius: "20000",
    edge: "Luxury market—premium pet-safe services",
    focusService: "Premium Pet-Safe Deep Cleaning",
    reviewFocus: "luxury home cleaning",
    searchVolume: "low",
  },
  Florence: {
    lat: "34.7998",
    lng: "-87.6772",
    phone: "+1-256-826-1100",
    state: "Alabama",
    stateAbbr: "AL",
    zips: "35630-35634",
    radius: "30000",
    edge: "Smaller market (less comp)—pet-safe niche can claim strong pack share",
    focusService: "Pet-Safe House Cleaning",
    reviewFocus: "reliable local service",
    searchVolume: "low",
  },
  "Muscle Shoals": {
    lat: "34.7448",
    lng: "-87.6675",
    phone: "+1-256-826-1100",
    state: "Alabama",
    stateAbbr: "AL",
    zips: "35661-35662",
    radius: "35000",
    edge: "Shoals area consolidation—one provider advantage",
    focusService: "Pet-Safe House Cleaning",
    reviewFocus: "local trusted team",
    searchVolume: "low",
  },
  Nashville: {
    lat: "36.1627",
    lng: "-86.7816",
    phone: "+1-615-510-1427",
    state: "Tennessee",
    stateAbbr: "TN",
    zips: "37201-37250",
    radius: "65000",
    edge: "High volume (2,900/mo)—no competitors use pet-safe/non-toxic schemas",
    focusService: "Non-Toxic House Cleaning",
    reviewFocus: "non-toxic eco cleaning",
    searchVolume: "very-high",
  },
  "West Nashville": {
    lat: "36.1527",
    lng: "-86.8816",
    phone: "+1-615-510-1427",
    state: "Tennessee",
    stateAbbr: "TN",
    zips: "37205-37209",
    radius: "25000",
    edge: "Luxury market—Belle Meade, Sylvan Park high-income households",
    focusService: "Luxury Home Cleaning",
    reviewFocus: "premium white-glove service",
    searchVolume: "medium",
  },
  Tuscumbia: {
    lat: "34.7312",
    lng: "-87.7025",
    phone: "+1-256-826-1100",
    state: "Alabama",
    stateAbbr: "AL",
    zips: "35674",
    radius: "35000",
    edge: "Historic homes niche—Helen Keller tourism creates cleaner demand",
    focusService: "Historic Home Cleaning",
    reviewFocus: "historic home care",
    searchVolume: "low",
  },
};

export const petSafeServiceCatalog = [
  {
    "@type": "Offer",
    itemOffered: {
      "@type": "Service",
      "@id": "https://thevalleycleanteam.com/#pet-safe-cleaning",
      name: "Pet-Safe House Cleaning",
      description: "Non-toxic, allergy-free cleaning for homes with pets. Safe for dogs, cats, and all furry family members.",
      provider: { "@id": "https://thevalleycleanteam.com/#organization" },
    },
    priceSpecification: {
      "@type": "PriceSpecification",
      price: 129.00,
      priceCurrency: "USD",
      description: "Starting price for 2-bedroom home",
    },
  },
  {
    "@type": "Offer",
    itemOffered: {
      "@type": "Service",
      "@id": "https://thevalleycleanteam.com/#deep-cleaning",
      name: "Pet-Safe Deep Cleaning",
      description: "Comprehensive top-to-bottom deep cleaning using pet-safe, non-toxic products. Includes baseboards, light fixtures, inside cabinets.",
      provider: { "@id": "https://thevalleycleanteam.com/#organization" },
    },
    priceSpecification: {
      "@type": "PriceSpecification",
      price: 199.00,
      priceCurrency: "USD",
      description: "Starting price",
    },
  },
  {
    "@type": "Offer",
    itemOffered: {
      "@type": "Service",
      "@id": "https://thevalleycleanteam.com/#regular-cleaning",
      name: "Recurring House Cleaning",
      description: "Weekly, biweekly, or monthly pet-safe cleaning service with consistent teams. Save up to 20%.",
      provider: { "@id": "https://thevalleycleanteam.com/#organization" },
    },
    priceSpecification: {
      "@type": "PriceSpecification",
      price: 99.00,
      priceCurrency: "USD",
      description: "Starting weekly price",
    },
  },
  {
    "@type": "Offer",
    itemOffered: {
      "@type": "Service",
      "@id": "https://thevalleycleanteam.com/#move-cleaning",
      name: "Pet-Safe Move In/Out Cleaning",
      description: "Complete move out and move in cleaning with pet-safe products. Get your deposit back or start fresh.",
      provider: { "@id": "https://thevalleycleanteam.com/#organization" },
    },
    priceSpecification: {
      "@type": "PriceSpecification",
      price: 199.00,
      priceCurrency: "USD",
      description: "Starting price",
    },
  },

  {
    "@type": "Offer",
    itemOffered: {
      "@type": "Service",
      "@id": "https://thevalleycleanteam.com/#office-cleaning",
      name: "Commercial & Office Cleaning",
      description: "Professional cleaning for offices, retail spaces, and commercial properties with flexible scheduling.",
      provider: { "@id": "https://thevalleycleanteam.com/#organization" },
    },
  },
  {
    "@type": "Offer",
    itemOffered: {
      "@type": "Service",
      "@id": "https://thevalleycleanteam.com/#airbnb-cleaning",
      name: "Airbnb & Vacation Rental Cleaning",
      description: "Fast turnaround cleaning for short-term rentals with guest-ready presentation.",
      provider: { "@id": "https://thevalleycleanteam.com/#organization" },
    },
  },
  {
    "@type": "Offer",
    itemOffered: {
      "@type": "Service",
      "@id": "https://thevalleycleanteam.com/#post-construction",
      name: "Post-Construction Cleaning",
      description: "Detailed cleaning after construction or renovation. Dust removal, window cleaning, move-in ready.",
      provider: { "@id": "https://thevalleycleanteam.com/#organization" },
    },
    priceSpecification: {
      "@type": "PriceSpecification",
      price: 300.00,
      priceCurrency: "USD",
      description: "Starting price",
    },
  },
];

export const cityReviewTemplates: Record<string, string> = {
  Huntsville: "Best pet-safe deep clean in Huntsville—house smells amazing, no allergies! Way better than Rocket Maids.",
  Madison: "Finally found a family-friendly cleaning service! Pet-safe products and consistent team every time.",
  Athens: "The Valley Clean Team did an incredible job before our house showing. Professional, thorough, and reliable!",
  Decatur: "Amazing move-out cleaning! Got our full deposit back. Pet-safe products were a huge plus.",
  "Mountain Brook": "Premium service for our luxury home. Attention to detail is unmatched. Worth every penny.",
  Florence: "Reliable cleaning service in the Shoals! They showed up on time and did an incredible job.",
  "Muscle Shoals": "Local team that knows the area. Trustworthy and thorough—highly recommend!",
  Nashville: "Non-toxic products that actually work! Finally a cleaning service that's safe for my pets and kids.",
  "West Nashville": "White-glove service for our Belle Meade home. Discreet, professional, and meticulous—exactly what we needed.",
  Tuscumbia: "They understand our historic home near Ivy Green. Gentle products, thorough work, and they respect the details of our century-old house.",
};

export const cityFAQs: Record<string, Array<{ q: string; a: string }>> = {
  Huntsville: [
    { q: "How does pet-safe cleaning work in Huntsville?", a: "We use non-toxic, EPA Safer Choice certified products that are safe for dogs, cats, and children. Our Huntsville team is trained in pet-safe protocols." },
    { q: "How far in advance should I book cleaning in Huntsville?", a: "We recommend booking 2–3 days in advance for the best availability. We also accommodate short-notice requests based on our schedule — call 256-826-1100 and we'll do our best to fit you in quickly." },
    { q: "What areas of Huntsville do you serve?", a: "We serve all Huntsville neighborhoods including Five Points, Twickenham, Monte Sano, Jones Valley, Hampton Cove, Big Cove, and Research Park." },
    { q: "How much does house cleaning cost in Huntsville?", a: "Our Huntsville house cleaning has base rates from $99 for recurring service and $149 for deep cleaning. Your exact price depends on your home's size and condition — we provide a free custom quote before we start." },
    { q: "Are your Huntsville cleaners insured and bonded?", a: "Yes, all Valley Clean Team members are fully insured with $2M liability coverage, bonded, and background-checked." },
    { q: "Do you clean homes with multiple pets in Huntsville?", a: "Absolutely! We specialize in homes with pets. Our pet-safe products eliminate odors without harmful chemicals." },
    { q: "What's included in a deep clean in Huntsville?", a: "Deep cleaning includes baseboards, light fixtures, inside cabinets, appliance exteriors, ceiling fans, and detailed bathroom/kitchen scrubbing." },
    { q: "Do you offer move-out cleaning in Huntsville?", a: "Yes, our Huntsville move-out cleaning helps you get your full deposit back. We clean everything landlords check." },
    { q: "How do I book a cleaning in Huntsville?", a: "Book online at thevalleycleanteam.com or call 256-826-1100. We offer free estimates and flexible scheduling." },
    { q: "Do you bring your own cleaning supplies to Huntsville homes?", a: "Yes, we bring all pet-safe, eco-friendly supplies and equipment. You don't need to provide anything." },
    { q: "Can I get recurring cleaning service in Huntsville?", a: "Yes! We offer weekly, biweekly, and monthly recurring cleaning with up to 20% savings and consistent teams." },
    { q: "Do you clean offices in Huntsville?", a: "Yes, we provide commercial cleaning for Huntsville offices, including Research Park businesses and medical facilities." },
    { q: "What makes Valley Clean Team different from other Huntsville cleaners?", a: "We're the only Huntsville cleaner specializing in pet-safe, non-toxic cleaning with flexible scheduling and 130+ 5-star reviews." },
    { q: "Do you offer Airbnb cleaning in Huntsville?", a: "Yes! We provide fast-turnaround Airbnb and vacation rental cleaning with guest-ready presentation for Huntsville hosts." },
    { q: "Are your cleaning products safe for allergies?", a: "Yes, our hypoallergenic, fragrance-free options are perfect for allergy sufferers. Many Huntsville customers choose us specifically for this." },
  ],
  Nashville: [
    { q: "Do you offer non-toxic house cleaning in Nashville?", a: "Yes! We specialize in non-toxic, pet-safe cleaning in Nashville using EPA Safer Choice certified products safe for pets and children." },
    { q: "What areas of Nashville do you serve?", a: "We serve Nashville neighborhoods including Belle Meade, Green Hills, Brentwood, Forest Hills, Oak Hill, 12 South, Sylvan Park, and Bellevue." },
    { q: "How much does house cleaning cost in Nashville TN?", a: "Our Nashville house cleaning starts at $129. We provide customized quotes based on your specific needs and home size." },
    { q: "How far in advance should I book cleaning in Nashville?", a: "We recommend booking 2–3 days ahead for the best availability. For short-notice requests, call our Nashville line at 615-510-1427 and we'll work to accommodate you based on current schedule." },
    { q: "Are you pet-friendly cleaners in Nashville?", a: "We're more than pet-friendly — we're pet-safe! Our Nashville team uses products that won't harm your pets." },
    { q: "Do you offer deep cleaning in Nashville?", a: "Yes, our Nashville deep cleaning is perfect for first-time clients or seasonal refreshing." },
    { q: "Is Valley Clean Team insured in Tennessee?", a: "Yes, we are fully licensed, insured, and bonded to operate in Nashville and throughout Tennessee." },
    { q: "Do you clean short-term rentals in Nashville?", a: "Yes! We offer professional turnover cleaning for Airbnb and VRBO hosts in the Nashville area." },
    { q: "What's included in a Nashville move-out clean?", a: "We cover all surfaces, inside appliances, cabinets, baseboards, and more to ensure your home is ready for the next occupant." },
    { q: "How do I schedule a cleaning in Nashville?", a: "You can book through our website or by calling 615-510-1427 for our Nashville-specific line." },
  ],
  Madison: [
    { q: "Do you serve all of Madison AL?", a: "Yes, we serve all Madison neighborhoods including Clift Farm, Town Madison, and areas near Madison Blvd." },
    { q: "Are your Madison cleaners pet-safe?", a: "Yes, we use the same non-toxic, pet-safe products in Madison as we do in all our service areas." },
    { q: "Do you offer recurring cleaning in Madison?", a: "Yes, many Madison families use our weekly or biweekly recurring services." },
  ],
  Florence: [
    { q: "Do you offer cleaning in Florence and the Shoals?", a: "Yes! We serve Florence, Muscle Shoals, Tuscumbia, and Sheffield with pet-safe cleaning." },
    { q: "How do I book cleaning in Florence AL?", a: "Book online at thevalleycleanteam.com or call 256-826-1100. We offer flexible scheduling including weekends and can often accommodate short-notice requests based on availability." },
  ],
};
